<?php
module_load_include('php', 'spectrum', 'includes/SpectrumIncludes');

function spectrum_menu()
{
	$items['admin/config/development/spectrum'] = array(
		'title' => 'Spectrum module settings',
		'description' => 'Settings here will influence the workings and performance of Spectrum',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('spectrum_admin'),
		'access arguments' => array('administer spectrum settings'),
		'type' => MENU_NORMAL_ITEM,
	);

    return $items;
}

function spectrum_admin()
{
	$form = array();

	$form['spectrum_development_mode'] = array(
		'#type' => 'checkbox',
		'#title' => t('Development Mode'),
		'#default_value' => variable_get('spectrum_development_mode', true),
		'#description' => t('Disabling development mode will drop validations, and will speed up the application'),
	);

	return system_settings_form($form);
}

function spectrum_admin_validate($form, &$form_state)
{

}

function spectrum_install()
{
	variable_set('spectrum_development_mode', 'true');
}

function spectrum_uninstall()
{
	variable_del('spectrum_development_mode');
}